"""remove enums for columns in db

Revision ID: 11f836ed7a79
Revises: 4151a7761703
Create Date: 2024-10-18 16:04:44.421681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11f836ed7a79'
down_revision: Union[str, None] = '4151a7761703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'name',
               existing_type=postgresql.ENUM('FULL_TIME', 'MOBILITY', name='applicationtype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('application_status', 'status',
               existing_type=postgresql.ENUM('CREATE', 'SENT', 'APPROVED', 'REJECTED', 'CANCELLED', 'FINISHED', 'IN_COUNCIL', 'IN_INSTITUTE', name='applicationstatustype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('vote', 'vote',
               existing_type=postgresql.ENUM('POSITIVE', 'NEGATIVE', 'ABSTENTION', 'CONSENSUS', name='votetype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('voting_status', 'name',
               existing_type=postgresql.ENUM('OPEN', 'APPROVED', 'DECLINED', name='votingstatustype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voting_status', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OPEN', 'APPROVED', 'DECLINED', name='votingstatustype'),
               existing_nullable=False)
    op.alter_column('vote', 'vote',
               existing_type=sa.String(),
               type_=postgresql.ENUM('POSITIVE', 'NEGATIVE', 'ABSTENTION', 'CONSENSUS', name='votetype'),
               existing_nullable=False)
    op.alter_column('application_status', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CREATE', 'SENT', 'APPROVED', 'REJECTED', 'CANCELLED', 'FINISHED', 'IN_COUNCIL', 'IN_INSTITUTE', name='applicationstatustype'),
               existing_nullable=False)
    op.alter_column('application', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FULL_TIME', 'MOBILITY', name='applicationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
