"""delete academic_unit_id of table rol

Revision ID: 2852677fff53
Revises: b50021caa067
Create Date: 2025-07-08 19:41:20.860841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rol_academic_unit_id_fkey'), 'rol', type_='foreignkey')
    op.drop_column('rol', 'academic_unit_id')
    op.create_index(op.f('ix_user_application_consecutive'), 'user_application', ['consecutive'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_application_consecutive'), table_name='user_application')
    op.add_column('rol', sa.Column('academic_unit_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rol_academic_unit_id_fkey'), 'rol', 'academic_unit', ['academic_unit_id'], ['id'])
    # ### end Alembic commands ###
