"""Add voting_status

Revision ID: 3345fbc8100b
Revises: e8e6812bd9bb
Create Date: 2024-10-15 19:15:10.619143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3345fbc8100b'
down_revision: Union[str, None] = 'e8e6812bd9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting_status',
    sa.Column('voting_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('OPEN', 'APPROVED', 'DECLINED', name='votingstatustype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['voting_id'], ['voting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('voting', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voting', sa.Column('status', postgresql.ENUM('OPEN', 'APPROVED', 'DECLINED', name='votingstatus'), autoincrement=False, nullable=False))
    op.drop_table('voting_status')
    # ### end Alembic commands ###
