"""add description in academic_unit

Revision ID: 363fdc263d47
Revises: 2852677fff53
Create Date: 2025-07-09 19:48:40.246158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363fdc263d47'
down_revision: Union[str, None] = '2852677fff53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_unit', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_unit', 'description')
    # ### end Alembic commands ###
