"""update enum

Revision ID: 4151a7761703
Revises: e5dd3cc92586
Create Date: 2024-10-17 21:39:05.977379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4151a7761703'
down_revision: Union[str, None] = 'e5dd3cc92586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationtype ADD VALUE 'MOBILITY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
