"""add applications

Revision ID: 430927dfd129
Revises: 97eba642c798
Create Date: 2024-10-05 15:39:06.046931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430927dfd129'
down_revision: Union[str, None] = '97eba642c798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status',
    sa.Column('name', sa.Enum('CREATE', 'SENT', 'APPROVED', 'REJECTED', 'CANCELLED', 'FINISHED', 'IN_COUNCIL', 'IN_INSTITUTE', name='applicationstatustype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('name', sa.Enum('FULL_TIME', name='applicationtype'), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('academic_unit_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_application',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('application_status_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['application_status_id'], ['application_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_application_academic_unit',
    sa.Column('user_application_id', sa.Uuid(), nullable=False),
    sa.Column('academic_unit_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_unit.id'], ),
    sa.ForeignKeyConstraint(['user_application_id'], ['user_application.id'], ),
    sa.PrimaryKeyConstraint('user_application_id', 'academic_unit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_application_academic_unit')
    op.drop_table('user_application')
    op.drop_table('application')
    op.drop_table('application_status')
    # ### end Alembic commands ###
