"""se agrega la tabla vote_type

Revision ID: 5c3dbaf983a6
Revises: 7439d5424792
Create Date: 2024-10-22 15:58:35.405845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3dbaf983a6'
down_revision: Union[str, None] = '7439d5424792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('voting', sa.Column('user_application_id', sa.Uuid(), nullable=False))
    op.drop_constraint('voting_application_id_fkey', 'voting', type_='foreignkey')
    op.create_foreign_key(None, 'voting', 'user_application', ['user_application_id'], ['id'])
    op.drop_column('voting', 'application_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voting', sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voting', type_='foreignkey')
    op.create_foreign_key('voting_application_id_fkey', 'voting', 'application', ['application_id'], ['id'])
    op.drop_column('voting', 'user_application_id')
    op.drop_table('vote_type')
    # ### end Alembic commands ###
