"""add represent research_group

Revision ID: 8d9373c7b13b
Revises: a56f72e40e71
Create Date: 2024-09-25 20:00:34.521452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9373c7b13b'
down_revision: Union[str, None] = 'a56f72e40e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('represent_research_group',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('research_group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'research_group_id')
    )
    op.drop_constraint('program_name_key', 'program', type_='unique')
    op.drop_column('program', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('program_name_key', 'program', ['name'])
    op.drop_table('represent_research_group')
    # ### end Alembic commands ###
