"""add action

Revision ID: 954b1def39bb
Revises: 5d2bb36c33f8
Create Date: 2025-03-11 21:58:36.359648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954b1def39bb'
down_revision: Union[str, None] = '5d2bb36c33f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_status', 'action')
    # ### end Alembic commands ###
