"""delete unique for email

Revision ID: 97eba642c798
Revises: 7da57a4632e3
Create Date: 2024-10-03 18:56:09.243519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97eba642c798'
down_revision: Union[str, None] = '7da57a4632e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('academic_unit_email_key', 'academic_unit', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('academic_unit_email_key', 'academic_unit', ['email'])
    # ### end Alembic commands ###
