"""delete column vote in vote

Revision ID: acea7a1ecfd3
Revises: c12e9fb0834c
Create Date: 2024-10-25 14:46:25.839560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acea7a1ecfd3'
down_revision: Union[str, None] = 'c12e9fb0834c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'vote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('vote', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
