"""Foreign key to academic_unit in rol

Revision ID: b33bb03a0872
Revises: 3caa57a6cd93
Create Date: 2024-09-27 19:51:40.590337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33bb03a0872'
down_revision: Union[str, None] = '3caa57a6cd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rol', 'academic_unit', ['academic_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rol', type_='foreignkey')
    # ### end Alembic commands ###
