"""agregar consecutivo

Revision ID: b50021caa067
Revises: 954b1def39bb
Create Date: 2025-04-03 15:32:03.566770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50021caa067'
down_revision: Union[str, None] = '954b1def39bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_application', sa.Column('consecutive', sa.Integer(), sa.Identity(always=False, start=5000, cycle=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_application', 'consecutive')
    # ### end Alembic commands ###
