"""se agrega la relacion vote-vote_type

Revision ID: c12e9fb0834c
Revises: 5c3dbaf983a6
Create Date: 2024-10-22 16:04:24.150362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12e9fb0834c'
down_revision: Union[str, None] = '5c3dbaf983a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('vote_type_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'vote', 'vote_type', ['vote_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_column('vote', 'vote_type_id')
    # ### end Alembic commands ###
