"""add is active for a user application in academic unit

Revision ID: e51aa852df29
Revises: acea7a1ecfd3
Create Date: 2025-02-06 22:46:26.185089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51aa852df29'
down_revision: Union[str, None] = 'acea7a1ecfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_application_academic_unit', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_application_academic_unit', 'is_active')
    # ### end Alembic commands ###
