"""update name to status in application status

Revision ID: e5dd3cc92586
Revises: 3345fbc8100b
Create Date: 2024-10-16 14:42:43.072361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5dd3cc92586'
down_revision: Union[str, None] = '3345fbc8100b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status', sa.Column('status', sa.Enum('CREATE', 'SENT', 'APPROVED', 'REJECTED', 'CANCELLED', 'FINISHED', 'IN_COUNCIL', 'IN_INSTITUTE', name='applicationstatustype'), nullable=False))
    op.drop_column('application_status', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status', sa.Column('name', postgresql.ENUM('CREATE', 'SENT', 'APPROVED', 'REJECTED', 'CANCELLED', 'FINISHED', 'IN_COUNCIL', 'IN_INSTITUTE', name='applicationstatustype'), autoincrement=False, nullable=False))
    op.drop_column('application_status', 'status')
    # ### end Alembic commands ###
