"""invertir relacion application_status

Revision ID: e8e6812bd9bb
Revises: 901b4b8bf4be
Create Date: 2024-10-11 16:56:13.789229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e6812bd9bb'
down_revision: Union[str, None] = '901b4b8bf4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status', sa.Column('user_application_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'application_status', 'user_application', ['user_application_id'], ['id'])
    op.drop_constraint('user_application_application_status_id_fkey', 'user_application', type_='foreignkey')
    op.drop_column('user_application', 'application_status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_application', sa.Column('application_status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_application_application_status_id_fkey', 'user_application', 'application_status', ['application_status_id'], ['id'])
    op.drop_constraint(None, 'application_status', type_='foreignkey')
    op.drop_column('application_status', 'user_application_id')
    # ### end Alembic commands ###
