services:
    redis:
        container_name: 'redis'
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - siga-fcen

    celery_worker:
        container_name: "celery_worker"
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: celery -A app.core.celery_worker.celery_app worker --loglevel=info -Q test-queue -c 1
        env_file:
            - ../.env
        depends_on:
            - redis
            - backend
        networks:
            - siga-fcen

    celery_beat:
        container_name: 'celery_beat'
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: celery -A app.core.celery_worker.celery_app worker --loglevel=info
        env_file:
            - ../.env
        depends_on:
            - redis
            - backend
        networks:
            - siga-fcen

    flower:
        container_name: "flower"
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: celery -A app.core.celery_worker.celery_app flower --port=5555
        env_file:
            - ../.env
        ports:
            - "5555:5555"
        depends_on:
            - celery_worker
        networks:
            - siga-fcen

    backend:
        container_name: 'backend-siga'
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8003
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8003:8003"
        expose:
            - "8003"
        env_file:
            - ../.env
        networks:
            - siga-fcen
        restart: on-failure

networks:
  siga-fcen:
    external: True
